'use client'

import { X, Copy, Check, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import type { Story } from '@/types'

const typeColors: Record<Story['story_type'], string> = {
  pmu: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  explainer: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  faq: 'bg-amber-50 text-amber-700 border-amber-200',
  comparison: 'bg-violet-50 text-violet-700 border-violet-200',
}

const typeLabels: Record<Story['story_type'], string> = {
  pmu: 'PMU',
  explainer: 'Explainer',
  faq: 'FAQ',
  comparison: 'Comparison',
}

interface StoryDetailProps {
  story: Story
  onClose: () => void
}

export function StoryDetail({ story, onClose }: StoryDetailProps) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(story.content)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback: ignore
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge className={typeColors[story.story_type]}>
            {typeLabels[story.story_type]}
          </Badge>
          <Badge variant="outline" className="text-xs">
            {story.audience}
          </Badge>
        </div>
        <Button
          variant="ghost"
          size="icon-xs"
          onClick={(e) => {
            e.stopPropagation()
            onClose()
          }}
          aria-label="Collapse story"
        >
          <X className="size-4" />
        </Button>
      </div>

      <h3 className="text-xl font-semibold text-[var(--st-text)]">{story.title}</h3>

      <div className="max-h-96 overflow-y-auto pr-1">
        <p className="text-sm leading-relaxed text-[var(--st-text-muted)] whitespace-pre-line">
          {story.content}
        </p>
      </div>

      <div className="flex items-center justify-between border-t border-[var(--st-border)] pt-3">
        <Button
          variant="outline"
          size="sm"
          onClick={(e) => {
            e.stopPropagation()
            handleCopy()
          }}
        >
          {copied ? (
            <Check className="size-3.5 text-emerald-500" />
          ) : (
            <Copy className="size-3.5" />
          )}
          {copied ? 'Copied' : 'Copy Full Content'}
        </Button>
        <span className="flex items-center gap-1 text-[10px] text-[var(--st-text-muted)]/60">
          <Sparkles className="size-3" />
          Generated by Regen AI
        </span>
      </div>
    </div>
  )
}
